### ISSUE TITLE
FileNotFoundError:[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by binaryghost10** [r0oth3x49/udemy-dl#48] opened 2017-12-14 12:48 UTC
Not sure if due to file path length.

![image](https://user-images.githubusercontent.com/34542924/33993103-1e8097e4-e110-11e7-952a-ac04f55d3d53.png)

**Comment by r0oth3x49** [comment] 2017-12-14 18:00
@binaryghost10 thanks for the report but this is duplicate of #32 so i 'm closing the issue solution is already  described.

**Closed by r0oth3x49** 2017-12-14 18:00 UTC
