### ISSUE TITLE
Please Help!!!

### ISSUE THREAD

**Issue by thedtech** [r0oth3x49/udemy-dl#150] opened 2018-03-13 14:56 UTC
Hello Sir,
              Sorry, If I am asking a noob question. Actually your script is running very well with Python 3.6.4 installed on my system. But I am currently learning Python Programming, Due to which I have to install ANACONDA PYTHON on my system but whenever I install Anaconda on my system, Script starts to give following errror:

**udemy-dl.py: error: the following arguments are required: course**

With only python installed, script is running very well but with Anaconda above error starts to appear. This error only comes with Anaconda either it is stand alone or with python. Only way for me to run this script is stand alone python without Anaconda. PLEASE HELP ME TO RUN THIS SCRIPT WITH ANACONDA ALSO!!!

Thank You.

**Comment by tofanelli** [comment] 2018-03-13 18:46
install docker to use Anaconda =)... no?

**Comment by thedtech** [comment] 2018-03-14 04:00
@tofanelli I have installed Docker but I don't know what to do next. Can't I run this script with docker? if yes, then please tell me the next steps. Is it necessary to run Anaconda with Docker to run this script?

If there is a simple way to run this script while Anaconda installed on system then please please tell me. extremely sorry if I am annoying you with these noob questions but please help if you can, to run this script in a simple way with anaconda installed.

Thank You.

**Comment by r0oth3x49** [comment] 2018-03-14 07:37
@thedtech you are facing that error because course URL is positional argument so it need to be provide either way. i really didn't tested the script with Anaconda installation so i 'm sorry my brother i cannot help you with that. i would really appreciate if some else can.

**Comment by tofanelli** [comment] 2018-03-14 16:29
@thedtech .... docker is a way to virtualize an OS inside your computer with some cool things... you will need go to docker website, find a container with python, go to your terminal, ask for download and install and then use it

**Comment by r0oth3x49** [comment] 2018-03-16 07:27
@thedtech i 'm considering that the problem is solved for you and closing the issue but other can also suggest there solution to this issue.

**Closed by r0oth3x49** 2018-03-16 07:27 UTC
Labels: help-wanted
