### ISSUE TITLE
downloading issue

### ISSUE THREAD

**Issue by iamgovindthakur** [r0oth3x49/udemy-dl#412] opened 2019-07-21 08:24 UTC
only video and subtitle is downloading study materials file is not downloading how to download that

**Comment by r0oth3x49** [comment] 2019-07-27 08:08
@iamgovindthakur can you follow the issue repording guideline. this should not be the case i can't reproduce.

and if by study materials you mean quizzes so those are out of scope & i will not add support for downloading quizzes.

**Closed** 2019-07-27 08:12 UTC
Labels: incomplete
