### ISSUE TITLE
Download error:  reason _exit_

### ISSUE THREAD

**Issue by MatterSec** [r0oth3x49/udemy-dl#458] opened 2019-12-11 19:37 UTC
Describe the issue
Course download, but error on download. I have tried this using password and now using cookie and getting the follow issue. I see https://github.com/r0oth3x49/udemy-dl/issues/444 was recently closed, but same error occurring. Tried with multiple courses including free ones and paid which I have subscribed to. - Repo downloaded 1 hour ago.

To Reproduce
- https://www.udemy.com/course/the-complete-internet-security-privacy-course-volume-1
- https://www.udemy.com/course/python-for-ethical-hacking-develop-pentesting-tools/
I'm using cookies - Tried with username and password as well.

Command:
python udemy-dl.py https://www.udemy.com/course/the-complete-internet-security-privacy-course-volume-1/ -k cookie.txt

error:
[https://prnt.sc/q9i3w9](https://prnt.sc/q9i3w9)

Python Environment (please complete the following information):
Kali - 2019.4
Python 2.7.17 & Python 3.7.5

Additional:
Tried on 5+ courses..
Thanks

**Comment by k3tzor** [comment] 2020-01-03 09:22
I have the same issue and can't find a solution. Tried the same things.

**Comment by priyavadan** [comment] 2020-01-08 02:39
same issue for me

**Comment by r0oth3x49** [comment] 2020-01-31 13:44
did you guys tried to updates requests library? the issue is specific to may be python or requests not udemy-dl, because context manager is not working properly for you guys while here i can't reproduce the error

**Comment by r0oth3x49** [comment] 2020-02-02 06:41
closing the issue as i can't reproduce the error.

**Closed by r0oth3x49** 2020-02-02 06:41 UTC
Labels: cant-reproduce
