### ISSUE TITLE
Download failed with 'Too many open files'

### ISSUE THREAD

**Issue by nayavu** [r0oth3x49/udemy-dl#470] opened 2020-02-01 11:26 UTC
On a  linux machine, for big Udemy courses (for example, https://www.udemy.com/course/beginning-c-plus-plus-programming/), it fails with 'Too many open files' after ~100 lectures.
```
Reason : [('system library', 'fopen', 'Too many open files'),
```

My ulimit is `1024`, I obviously can increase it but the issue is probably somewhere in the code as it feels like there's a file descriptor leak.

**Comment by r0oth3x49** [comment] 2020-02-02 06:49
i have already taken care of files opening. 'm doing that with context managers hopefully it clarifies the issue is more specific to system and it was reported so many times earlier i closed it because i was not able to reproduce it the error. plus there is only one thing where i 'm using codecs pkg to open file and write to it and that function will only be called if a course has externals links to assets. i will take a look at it and change the code to use the context managers, Still i 'm sure the error is more specific to the OS you are using, But i will check and try to fix it ASAP.


so i 'm going to close this issue.

**Closed by r0oth3x49** 2020-02-02 06:49 UTC

**Comment by Marty** [comment] 2020-05-15 11:13
@r0oth3x49 Loving this tool!
But I experience the same behaviour. After "some" time the download of a long course fails.

Also I see a continuous increase in open file handles (lsof -p <PID> | wc -l) leading to the conclusion that they are not closed properly and remain open.

My `file-max` is pretty large:
```
cat /proc/sys/fs/file-max
787572
```
and is not reached at all
```
sof | wc -l
276234
```
So the process runs into the soft limit
```
ulimit -Sn
1024
```
But over a thousand open file handles is not normal.
One could prevent this maybe by skipping subtitles as they multiply the files downloaded for each lecture quite a bit.

**Comment by r0oth3x49** [comment] 2020-05-16 06:39
@Marty still using the context manager to download files and save, i guess that should have done the work for us as context manager are used for auto closing the file once done.

how i can reproduce the error?
