### ISSUE TITLE
No Audio in Videos

### ISSUE THREAD

**Issue by phyzixmusic** [r0oth3x49/udemy-dl#168] opened 2018-04-07 19:53 UTC
Everything works like a charm but the videos have no audio :( 
Please assist me

**Comment by r0oth3x49** [comment] 2018-04-08 08:57
@phyzixmusic i just checked i cannot reproduce. for me it is working fine so i 'm closing this issue with invalid.

**Closed by r0oth3x49** 2018-04-08 08:57 UTC
