### ISSUE TITLE
error when wanting to download

### ISSUE THREAD

**Issue by YaNgO15** [r0oth3x49/udemy-dl#99] opened 2018-02-12 07:36 UTC
error when wanting to download, my account has the correct password and gmail

Traceback (most recent call last):
  File "udemy-dl.py", line 924, in <module>
    main()
  File "udemy-dl.py", line 831, in main
    udemy.ExtractAndDownload(caption_only=True)
  File "udemy-dl.py", line 291, in ExtractAndDownload
    self.login()
  File "udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "C:\Users\Levi\udemy-dl-master\udemy\_extractor.py", line 147, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "C:\Users\Levi\udemy-dl-master\udemy\_extractor.py", line 98, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "C:\Users\Levi\udemy-dl-master\udemy\_extractor.py", line 88, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "C:\Users\Levi\udemy-dl-master\udemy\_utils.py", line 80, in _hidden_inputs
    html = re.sub(r'', '', html)
  File "C:\Python27\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by r0oth3x49** [comment] 2018-02-12 08:11
@YaNgO15 i have tested against python2 it works fine for me. i 'm closing this issue as duplicate #98 to discuss this is a single issue.

**Closed by r0oth3x49** 2018-02-12 08:11 UTC

**Comment by yashjit** [comment] 2018-02-12 09:04
No Luck for me.
Using MAC -10.15
Python - 2.7
-------------------------------------------------------------------------
[-] Unable to extract login-form form
Traceback (most recent call last):
  File "udemy-dl.py", line 924, in <module>
    main()
  File "udemy-dl.py", line 856, in main
    udemy.ExtractAndDownload(path=outto, quality=res)
  File "udemy-dl.py", line 291, in ExtractAndDownload
    self.login()
  File "udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "/Yashjit/Udemy/udemy-dl/udemy/_extractor.py", line 147, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "/Yashjit/Udemy/udemy-dl/udemy/_extractor.py", line 98, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "/Yashjit/Udemy/udemy-dl/udemy/_extractor.py", line 88, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "/Yashjit/Udemy/udemy-dl/udemy/_utils.py", line 80, in _hidden_inputs
    html = re.sub(r'', '', html)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by yashjit** [comment] 2018-02-12 09:10
From cffi callback <function _verify_callback at 0x1083d7d70>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
[-] : Connection error : make sure your internet connection is working.

**Comment by r0oth3x49** [comment] 2018-02-12 09:26
@yashjit you should update your python installation and then follow the steps.

- sudo pip install requests[security]

or install virtualenv and in that install the requirements and requests[security].

i have tested on MAC as well with py2 and py3 works fine for me i cannot reproduce the above error.

**Comment by YaNgO15** [comment] 2018-02-12 16:59
it does not work on me with py2 and py3 on windows 10 :(


![no funiona](https://user-images.githubusercontent.com/34865634/36109025-321b7ff2-0fec-11e8-9963-fd5e9d612e9f.png)

**Comment by r0oth3x49** [comment] 2018-02-12 17:57
@YaNgO15 have a look it is working fine.
![capture](https://user-images.githubusercontent.com/11024397/36111426-e2960d06-1047-11e8-9830-9d2d6f99a397.PNG)

try to install each requirement one by one with `--upgrade` option.
example.
pip install requests[security] --upgrade
