### ISSUE TITLE
现在只能下载试看部分了。看来改变了加密策略

### ISSUE THREAD

**Issue by yuanhang110** [r0oth3x49/udemy-dl#631] opened 2021-04-24 09:54 UTC
**Describe the bug**
Only the trial part can be downloaded now. It seems that the encryption strategy has been changed

python udemy-dl.py https://www.udemy.com/course/deeplearning/ -k 1.txt -o "C:/"

**Python Environment (please complete the following information):**
 - OS Platform: [Windows 10]
 - Python Version [e.g. 3.9]

**Additional context**
![image](https://user-images.githubusercontent.com/39437291/115954846-bdb41200-a525-11eb-87df-c50e0a93b1c1.png)
![QQ截图20210424175201](https://user-images.githubusercontent.com/39437291/115954856-cb699780-a525-11eb-9a3b-64d07e9c6afd.jpg)

**Comment by r0oth3x49** [comment] 2021-04-24 12:30
more related or same to #627 as the cause is same so closing the issue as dup

**Closed by r0oth3x49** 2021-04-24 12:30 UTC
