### ISSUE TITLE
Cookies error

### ISSUE THREAD

**Issue by jcemos57** [r0oth3x49/udemy-dl#500] opened 2020-05-04 18:46 UTC
When I try to download course after inputing my udemy username and password it give me error see screenshot attached.
![udemy cmd error](https://user-images.githubusercontent.com/57722976/81001641-f7d16300-8e3f-11ea-966e-620d48bf69be.PNG)

**Comment by ahmedwahdan** [comment] 2020-05-06 13:31
I face the same error.

**Comment by penCsharpener** [comment] 2020-05-06 19:34
yes, same here

**Comment by amitjpr** [comment] 2020-05-07 11:42
I am also facing same issue, can you please provide steps ,how you (@penCsharpener ) resolve it

**Comment by dillagr** [comment] 2020-05-07 11:46
try the procedure here: https://hive.blog/udemy/@dillagr/udemy-trick-you-must-try-workaround

**Comment by jcemos57** [comment] 2020-05-08 03:43
@dillagr thanks for the solution i really appreciate.

**Comment by r0oth3x49** [comment] 2020-05-09 00:29
it seems the problem is solved with `-k` switch closing the issue.

**Closed by r0oth3x49** 2020-05-09 00:29 UTC
