### ISSUE TITLE
Error downloading course

### ISSUE THREAD

**Issue by ankeorum** [r0oth3x49/udemy-dl#336] opened 2019-03-04 15:49 UTC
[*] : Lecture(s) : (2 of 4)
[*] : Downloading (038 Tipos de enfoques del Hacking Etico)
[*] : Lecture : '038 Tipos de enfoques del Hacking Etico' (download skipped).
[-] : URLError : either your internet connection is not working or server aborted the request

[*] : Lecture(s) : (3 of 4)
[*] : Downloading (039 Diferentes tipos de testeos de Hacking Etico y que se debe entregar)
[*] : Lecture : '039 Diferentes tipos de testeos de Hacking Etico y que se debe entregar' (download skipped).
[-] : URLError : either your internet connection is not working or server aborted the request

[*] : Lecture(s) : (4 of 4)
[*] : Downloading (040 [TIP CEVICAS] a clientes de Cevicas.com robustecer sus contrasenas)
[*] : Lecture : '040 [TIP CEVICAS] a clientes de Cevicas.com robustecer sus contrasenas' (download skipped).
[-] : URLError : either your internet connection is not working or server aborted the request

[*] : Downloading chapter : (9 of 9)
[+] : Chapter (09 Las implicaciones de los crimenes por computadora y resumen del curso)
[*] : Found (4) lectures ...

[*] : Lecture(s) : (1 of 4)
[*] : Downloading (041 Los crimenes por computadora y sus implicaciones)
[*] : Lecture : '041 Los crimenes por computadora y sus implicaciones' (download skipped).
[-] : URLError : either your internet connection is not working or server aborted the request

[*] : Lecture(s) : (2 of 4)
[*] : Downloading (042 Cierre del Escenario de inicio y resumen)
[*] : Lecture : '042 Cierre del Escenario de inicio y resumen' (download skipped).
[-] : URLError : either your internet connection is not working or server aborted the request

[*] : Lecture(s) : (3 of 4)
[*] : Downloading (043 Agradecimiento despedida e invitacion al nuevo curso Footprinting o Reconocimi)
[*] : Lecture : '043 Agradecimiento despedida e invitacion al nuevo curso Footprinting o Reconocimi' (download skipped).
[-] : URLError : either your internet connection is not working or server aborted the request

[*] : Lecture(s) : (4 of 4)
[*] : Downloading (044 Presentacion curso 2 - Reconocimiento de Objetivos  Cupon descuento)
[*] : Lecture : '044 Presentacion curso 2 - Reconocimiento de Objetivos  Cupon descuento' (download skipped).
[-] : URLError : either your internet connection is not working or server aborted the request

Those are the errors and code executed is:
python udemy-dl.py https://www.udemy.com/fundamentos-del-hacking-etico-profesional/learn/v4/t/lecture/8099998?start=47

Is not a free course so maybe you cannot replicate with same course but any paid course would get these errors, I think.

Can anyone assist?

**Comment by r0oth3x49** [comment] 2019-03-05 07:25
@ankeorum if i 'm not able to produce the error i would need your account credentials to reproduce and fix. If you are not okay sharing your creds then i will close the issue.

**Comment by ankeorum** [comment] 2019-03-05 10:45
Send me your personal e-mail and I will provide you with my credentials

**Comment by r0oth3x49** [comment] 2019-03-05 15:49
[here you go](mailto:nasir251292@gmail.com). by the way its also written on the profile.

**Comment by rpgrca** [comment] 2019-03-09 02:45
I also have this error, I just kill the application and wait a few hours, sometimes a day to try again, and it works again.

**Comment by r0oth3x49** [comment] 2019-03-09 10:04
@ankeorum i 'm unable reproduce the error you are facing for me its working fine. take a look at POC below.
The reason you are facing the above error might be direct download url got expired if you retry downloading then the tool will work fine. tell me if this is not the case?
![Capture](https://user-images.githubusercontent.com/11024397/54069841-984be780-427c-11e9-9583-b1f0314f674c.PNG)

**Comment by ShinIce** [comment] 2019-03-10 11:47
I went through all my courses and there isn't one who downloads the video. All of them have the same error with "**URLError : either your internet connection is not working or server aborted the request**"

There is no change if I use user&pw, cookies, resolution or download location. But if I dump the links with **--save** then those works fine and I can download it, so where is the problem?
Passing you my (or our) login credentials is not the best way to fix problems imho :unamused:

**Comment by r0oth3x49** [comment] 2019-03-10 20:03
@ShinIce What do you think what should i provide?

**Comment by ankeorum** [comment] 2019-03-14 15:37
@r0oth3x49 could you tell me what is the link you are using to get the udemy videos?

**Comment by r0oth3x49** [comment] 2019-03-14 19:12
@ankeorum here it is --> `https://www.udemy.com/fundamentos-del-hacking-etico-profesional/`

**Comment by r0oth3x49** [comment] 2019-03-19 16:10
@ankeorum i 'm going to close the issue as i can't reproduce and there are no words from your side as well.

**Closed by r0oth3x49** 2019-03-19 16:10 UTC
Labels: cant-reproduce

**Comment by ankeorum** [comment] 2019-03-19 17:30
Ok thanks for your help. Will get back to this when have some time

Gonzalo López
IT Systems Administrator

________________________________
