### ISSUE TITLE
Failure to retrieve course information after successful login

### ISSUE THREAD

**Issue by hdupre** [r0oth3x49/udemy-dl#174] opened 2018-04-17 20:16 UTC
I am receiving the following error on a specific course (udemy.com/the-web-developer-bootcamp). I downloaded four other courses today without issue.

Here is the error message:

Trying to login as (user@gmail.com)...
[+] : Logged in successfully.
Traceback (most recent call last):on .. 
  File "udemy-dl.py", line 1201, in <module>
    main()
  File "udemy-dl.py", line 1042, in main
    udemy.course_download(path=options.output, quality=options.quality)
  File "udemy-dl.py", line 393, in course_download
    course = udemy.course(self.url, self.username, self.password)
  File "/Users/user/udemy-dl/udemy/_udemy.py", line 37, in course
    return Udemy(url, username, password, basic, callback)
  File "/Users/user/udemy-dl/udemy/_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "/Users/user/udemy-dl/udemy/_shared.py", line 61, in __init__
    self._fetch_course()
  File "/Users/user/udemy-dl/udemy/_internal.py", line 54, in _fetch_course
    self._info              =       self._real_extract(self._url)
  File "/Users/user/udemy-dl/udemy/_extract.py", line 313, in _real_extract
    course_json = self._extract_course_json(course_id)
  File "/Users/user/udemy-dl/udemy/_extract.py", line 113, in _extract_course_json
    resp = self._session._get(url).json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by r0oth3x49** [comment] 2018-04-21 11:07
@hdupre i 'm considering that this is solved for you so i 'm going to close the issue as i cannot reproduce for me it works fine.

**Closed by r0oth3x49** 2018-04-21 11:07 UTC
Labels: cant-reproduce

**Comment by zzzykf** [comment] 2018-06-18 14:02
same issue here.
I can't download the Spring & Hibernate for Beginners chapter 46 and 47.
Other chapters I can download without any issue.
@r0oth3x49

**Comment by hdupre** [comment] 2018-06-18 15:49
I fixed this issue by downloading the newest version of udemy-dl.

**Comment by zzzykf** [comment] 2018-06-18 15:55
I'm using the latest version of udemy-dl.
