### ISSUE TITLE
"Unable to extract login-form form" & "You do not have permission to perform this action"

### ISSUE THREAD

**Issue by Nocxy** [r0oth3x49/udemy-dl#270] opened 2018-08-24 15:36 UTC
Hi everyone,

When I try to download with udemy-dl, I get `Unable to extract login-form form`.

I updated the packages:

- sudo pip install requests --upgrade
- sudo pip install unidecode --upgrade
- sudo pip install requests[security] --upgrade

What should I do?

Thanks in advance.

**Comment by Nocxy** [comment] 2018-08-24 15:43
I foun

**Comment by Nocxy** [comment] 2018-08-24 15:51
It seems like Udemy detects download attempts so I'll wait and see.

**Comment by Nocxy** [comment] 2018-08-24 16:02
I waited a couple of minutes and just retried now. I got: `Udemy Says : You do not have permission to perform this action. Run udemy-dl against course within few seconds.`

**Comment by r0oth3x49** [comment] 2018-08-25 17:49
@Nocxy i cannot reproduce the error. please follow issue reporting guideline.

**Comment by Avidexp** [comment] 2018-08-31 16:45
I believe this is a Linux related issue. I can attest I'm having the same problems. 

I'll work on trying to gather proper docs for reproduction of error, but I believe this is a legitimate issue that should be investigated.

**Comment by r0oth3x49** [comment] 2018-08-31 17:27
@Avidexp this error would most likely occur if SSL version is out dated. otherwise this is a simple handle to the exception if udemy API does not return any information against course it mean either you are not enrolled in course or udemy Server is not accepting request. i cannot reproduce the above error i tried on Ubuntu, Mac, CentOS, Windows 7/8/10.

**Comment by r0oth3x49** [comment] 2018-09-02 11:44
@Nocxy i cannot reproduce and there is no update from you as well so i 'm closing this issue now.

**Closed by r0oth3x49** 2018-09-02 11:44 UTC
Labels: cant-reproduce, incomplete

**Comment by ArjonBu** [comment] 2018-09-02 12:05
I am having this issue too. How can I help to provide more information?

**Comment by ArjonBu** [comment] 2018-09-02 12:06
It is working now. It might be some temporary lock by udemy.
