### ISSUE TITLE
Download (looks) finished but cant find the files

### ISSUE THREAD

**Issue by puntodamar** [r0oth3x49/udemy-dl#537] opened 2020-07-24 17:15 UTC
Just like the title... the download reached the end of the course and the program exited by itself. But when i go to the download location i cant find the file.
I'm using a macbook and saved it to my external harddisk.
The command i used was :
`python udemy-dl.py https://www.udemy.com/course/arduino-sbs-17gs/ -k access_token.txt -o "/Volumes/rdisk2s1"`

At first I can locate the first 4 course section being downloaded. then I exited the program, and then called it again and the download resumed.

When I use "Get Info" i can confirm that the harddisk capacity was decreasing as I downloaded them, I just cant find the files.

I re-ran the program again and it says "already downloaded".

**Comment by r0oth3x49** [comment] 2020-07-24 20:16
strange how can i help you in this situation which i have never ever faced

**Comment by puntodamar2** [comment] 2020-07-24 23:06
I tried to re-download everything again without exiting the program and it's the same. Tried to plugged the harddisk to my windows and all the files are present.

So the bug is either on macbook or the NTFS compability app which I used.

**Comment by puntodamar2** [comment] 2020-07-24 23:18
Update : tried to open the harddisk in read-only mode (without app to enable writing) and the files are present.
So it's because the app im using. Hasleo NTFS for Mac.

Thank you.

**Comment by r0oth3x49** [comment] 2020-07-25 11:56
okay great it seems the issue is now resolve for you i 'm going to close it now.

**Closed by r0oth3x49** 2020-07-25 11:56 UTC
