### ISSUE TITLE
Unable to extract login-form

### ISSUE THREAD

**Issue by ipkpjersi** [r0oth3x49/udemy-dl#177] opened 2018-04-19 21:55 UTC
Whenever I try to download a course, I get:

[-] Unable to extract login-form form

**Comment by r0oth3x49** [comment] 2018-04-20 05:02
i cannot reproduce for me it is working fine.
![capture](https://user-images.githubusercontent.com/11024397/39031482-ea34e3fc-4481-11e8-837b-d03d084fa616.PNG)

**Comment by ochrstn** [comment] 2018-04-20 08:50
I had the same error but a few minutes later it was working again without changing anything.

**Comment by ipkpjersi** [comment] 2018-04-20 12:27
I am not sure what is happening but I am definitely getting this issue. It seems I keep getting captcha after downloading like one course, I am not sure if my account is permanently flagged but udemy-dl is essentially useless to me as I literally cannot use it anymore. I went to an empty directory, with a VPN with an IP I don't normally use on this account, downloaded one course and got connection reset by peer, so I tried to start the download again but I got the [-] Unable to extract login-form form again.

Can you possibly set a delay or something between downloading episodes?

**Comment by seanwhe** [comment] 2018-04-20 14:59
Yip definitely something amiss all I get is

[-] Unable to extract login-form form

After I leave the attempt for some time I am able to download again

**Comment by r0oth3x49** [comment] 2018-04-21 10:56
@ipkpjersi as this is working for you now and i can't reproduce the error so i 'm going to close the issue now.

**Closed by r0oth3x49** 2018-04-21 10:56 UTC
Labels: cant-reproduce

**Comment by ipkpjersi** [comment] 2018-04-21 19:49
@r0oth3x49 

I mean, it's not quite solved. Having proxy support and support for a delay between episodes downloading would go a long way against their new anti-downloading measures. 

I have implemented a 20 second delay with the "sleep" command on Linux between downloading courses and it has helped until it started happening again, so then I waited a couple hours and increased it to a 60 second delay between downloading courses. Hopefully I do not need to increase the delay between downloading courses any more, but luckily this is still better than downloading from Pluralsight where you have to have a 15 minute delay between downloading episodes and between downloading courses.
