### ISSUE TITLE
Cannot download from udemy for business accounts

### ISSUE THREAD

**Issue by TechieGenie** [r0oth3x49/udemy-dl#180] opened 2018-04-26 10:39 UTC
Hi, I am unable to download the videos from udemy for business accounts where a particular subdomain name comes before udemy.com

I think currently there are no handlers which could download from business accounts. I have just now signed up for business account where they give access to all videos for free for 14 days and I just wanna download them all :grin: 

Please fix this issue, it will be very very helpful.

**Comment by tithamane** [comment] 2018-04-26 10:57
I think this goes against the spirit of this downloader. Most of us buy courses on a regular and sometimes we need these courses offline for the times we know our internet is going to be really bad. But it seems like you want to just rip them off instead of supporting the content creators. Some of the content creators do a really good job and continue to do so as we support them.

Just my 2 cents.

**Comment by jaan143** [comment] 2018-04-26 11:08
@TechieGenie did they allow to watch all new programming courses ? or just selected courses from them ?

i want to buy business also but wanna know before

**Comment by r0oth3x49** [comment] 2018-04-26 12:41
@TechieGenie  i don't have access to any business subscription so i cannot test against the business account. but i have tested this against one of the business account in past days (creds was given by a friend on my email) it was working fine for me. if you want me to test it against your business subscription then you can email me your credentials.

**Comment by jaan143** [comment] 2018-04-26 15:49
@TechieGenie  i know bro but i just want to know that you can watch every course or just few courses which udemy team allow on business account

**Comment by r0oth3x49** [comment] 2018-04-27 05:45
@TechieGenie i cannot reproduce the error you are facing for me it works fine on business account as well. so i 'm going to close this issue as invalid. if you still face the error you can send me an [email](mailto:nasir251292@gmail.com)  we will discuss there.
here is a POC.
![capture](https://user-images.githubusercontent.com/11024397/39346488-cf3fbd7a-4a07-11e8-8739-9fac7e861735.PNG)

**Closed by r0oth3x49** 2018-04-27 05:45 UTC
Labels: account-needed

**Comment by subzer0x0** [comment] 2019-03-26 17:25
Thanks @r0oth3x49 for this excellent feature to download udemy videos offline from business account. I  tried with our business account in which it has SSO authentication enabled. It worked perfectly by adding **cookies** in the argument. 👍 

![business](https://user-images.githubusercontent.com/17097011/55018875-c02ba100-5019-11e9-88b8-ccdacc68deb7.png)

**Comment by raviswp** [comment] 2019-05-30 16:30
Hi @subzer0x0 
what are the steps do i need to follow if we have sso authentication. Please help me on this as earliest.

**Comment by subzer0x0** [comment] 2019-05-31 06:38
> 
> 
> Hi @subzer0x0
> what are the steps do i need to follow if we have sso authentication. Please help me on this as earliest.

1. Login to your Udemy business account and save the cookies in a text file
2. Use udemy-dl tool and specify **'-k'** flag with the cookie file name in command line. 

You should be able to download the courses as I mentioned in the screenshot earlier.

**Comment by iamgovindthakur** [comment] 2020-09-24 03:21
it's working 100% with business account i personally tried that have a look! thanks to the developer :)
![Screenshot (38)](https://user-images.githubusercontent.com/32303373/94096990-1b269a00-fe43-11ea-8710-6854aef1e6b5.png)

**Comment by mohd-tanveer** [comment] 2021-07-03 09:43
It doesn't download all the courses rather a few lectures

**Comment by subzer0x0** [comment] 2021-07-05 04:54
> It doesn't download all the courses rather a few lectures

It totally depends upon your corporate Udemy Subscription  and also few courses may not be published for business accounts.
