### ISSUE TITLE
Cannot login anymore

### ISSUE THREAD

**Issue by saisiddharth96** [r0oth3x49/udemy-dl#249] opened 2018-07-06 19:19 UTC
Hey,
I've been using the script for a while but for some reason I cannot login using the script anymore

**Comment by r0oth3x49** [comment] 2018-07-07 05:15
@saisiddharth96 you should check #184

**Comment by saisiddharth96** [comment] 2018-07-07 06:41
I believe that is a different issue, I'm getting "Failed to Login" error when i try to login even after a few hours

**Comment by r0oth3x49** [comment] 2018-07-07 09:15
then you should follow issue reporting guideline because for me it works fine i cannot reproduce. it may be caused by some typo so do check that as well.

**Comment by r0oth3x49** [comment] 2018-07-07 19:34
@saisiddharth96 here is POC where it works fine for me so i 'm closing this issue as invalid.
![capture](https://user-images.githubusercontent.com/11024397/42414038-a92e7898-8246-11e8-9c2e-5235e9e483aa.PNG)

**Closed** 2018-07-07 19:34 UTC
Labels: cant-reproduce, incomplete, invalid
