### ISSUE TITLE
SSLError(OSError(24, 'Too many open files'))

### ISSUE THREAD

**Issue by RiseT** [r0oth3x49/udemy-dl#563] opened 2020-09-23 06:57 UTC
**Describe the bug**
Script generally works like a charm, but when downloading a somewhat larger course (~ 15 hours) with many files, at one point the following error comes up for each subsequent file in the queue:

`ERROR ConnectionError: HTTPSConnectionPool(host='vtt-a.udemycdn.com', port=443): Max retries exceeded with url: [redacted] (Caused by SSLError(OSError(24, 'Too many open files')))`

When this started to happen, the number of downloaded files at that point were >= 1000 and total downloaded size of ~ 1 GB.

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] '...'
[redacted]

2. Run the following command to reproduce the error.
`python udemy-dl.py COURSE_URL -k cookie.txt`

3. See error
See above.

**Expected behavior**
No error, continued download.

**Screenshots**
n/a

**Python Environment (please complete the following information):**
 - OS Platform: [e.g. Windows 10, Ubuntu 16.04, macOS Sierra]
Linux Mint 20 (based on Ubuntu 20.04)

 - Python Version [e.g. 3.x.x]
3.8.5

**Additional context**
n/a

**Comment by r0oth3x49** [comment] 2020-09-23 12:57
@RiseT i might need an account tp reproduce the issue, i don't have any big course thus i cannot reproduce the error.
if you are okay with sharing your creds you can email me on weekend and i will take a look at it.
email to `nasir251292@gmail.com`

if you are not okay with sharing credentials then there is no way i can reproduce and i have to close issue as won't fix or you can close it by yourself.

**Closed** 2020-09-23 17:35 UTC
