### ISSUE TITLE
Unexpected error while downloading.

### ISSUE THREAD

**Issue by AnthonyIp** [r0oth3x49/udemy-dl#240] opened 2018-06-23 17:52 UTC
Hi ! 
I got some error which pop out when I'm downloading.

> Traceback (most recent call last):
>   File "/home/anthony/Documents/udemy-dl/udemy-dl.py", line 1441, in <module>
>     main()
>   File "/home/anthony/Documents/udemy-dl/udemy-dl.py", line 1437, in main
>     udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
>   File "/home/anthony/Documents/udemy-dl/udemy-dl.py", line 511, in course_download
>     self.download_lectures_and_captions(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=inner_index, lectures_count=lectures_count, lecture_subtitles=lecture_subtitles, lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
>   File "/home/anthony/Documents/udemy-dl/udemy-dl.py", line 427, in download_lectures_and_captions
>     self.download_subtitles(lecture_subtitles=lecture_subtitles, filepath=filepath, unsafe=unsafe)
>   File "/home/anthony/Documents/udemy-dl/udemy-dl.py", line 378, in download_subtitles
>     self.convert(filename=filename)
>   File "/home/anthony/Documents/udemy-dl/udemy/_vtt2srt.py", line 142, in convert
>     _start, _end  = m.group(1), m.group(2)
> AttributeError: 'NoneType' object has no attribute 'group'

I have it on 2 courses:
https://www.udemy.com/complete-android-n-developer-course/learn/v4/
and 
https://www.udemy.com/the-complete-android-oreo-developer-course/learn/v4/

**Comment by r0oth3x49** [comment] 2018-06-26 19:10
@AnthonyIp i might need your account to test against these courses and fix the problem for now you can also skip the subs with `--skip-subs` option

**Comment by AnthonyIp** [comment] 2018-06-26 21:51
@r0oth3x49 It works. So the issue was from the subs.

**Comment by r0oth3x49** [comment] 2018-06-27 06:04
@AnthonyIp can you please explain a bit more. is this working for you fine now or what?

**Comment by AnthonyIp** [comment] 2018-06-27 09:28
@r0oth3x49 By skipping the subs, I can download the video now but I can't download the substitles.

**Comment by CoderJolly** [comment] 2018-06-27 21:13
Hi!
This is exactly error i am getting, ignore the first 2 lines

<img width="682" alt="screen shot 2018-06-28 at 2 40 11 am" src="https://user-images.githubusercontent.com/25739036/41999893-9dc62acc-7a7c-11e8-8600-a1c27301a859.png">

**Comment by AnthonyIp** [comment] 2018-06-28 07:34
@CoderJolly from the last sentence of the output, I can guess you haven't installed colorama. 
Do a "sudo pip install -r requirement.txt" in the udemy-dl folder.

**Comment by r0oth3x49** [comment] 2018-06-29 12:21
@AnthonyIp as i said i cannot reproduce the error i might need your credentials to fix the error if you agree to share then please [email me](nasir251292@gmail.com) if not then i will close the issue and will w8 for others to report the same

**Closed** 2018-06-30 12:21 UTC
Labels: account-needed, cant-reproduce
