### ISSUE TITLE
Having Trouble Downloading Udemy is able to identify the requests sent from udemy-dl.

### ISSUE THREAD

**Issue by yashdeeph709** [r0oth3x49/udemy-dl#173] opened 2018-04-15 08:32 UTC
``
![image](https://user-images.githubusercontent.com/6427291/38776479-f23219ce-40b4-11e8-97fe-7829c01b4cf0.png)
Hi r0oth3x49,
I was using this tool for some days. I was able to download stuff before. But now I cannot download anything because they might have added some new cookie or something else to the request and they are able to identify the request is sent from python not the browser. I tried debugging it myself I found that when the _extract_course_id function tries to extract the course id from the webpage requested from the url provided This page is served which is why its unable to extract the course id. This udemy-dl is fantastic python script very well structured do tell me if you need help. you can also give me a direction and I will send you a pull request.

<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1"> <title>Access to this page has been denied.</title>   <link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel ="stylesheet"> <style> html,body{ margin: 0; padding: 0; font-family: 'Open Sans', sans-serif; color: #000; } a{ color: #c5c5c5; text-decoration: none; } .container{ align-items: center; display: flex; flex: 1; justify-content: space-between; flex-direction: column; height: 100%; } .container > div { width: 100%; display: flex; justify-content:center; } .container > div > div { display: flex; width: 80%; } .customer-logo-wrapper{ padding-top: 2rem; flex-grow: 0; background-color: #fff; visibility: hidden; } .customer-logo{ border-bottom: 1px solid #000; } .customer-logo > img{ padding-bottom: 1rem; max-height: 50px; max-width: auto; } .page-title-wrapper{ flex-grow: 2; } .page-title { flex-direction: column-reverse; } .content-wrapper{ flex-grow: 5; } .content{ flex-direction: column; } .page-footer-wrapper{ align-items: center; flex-grow: 0.2; background-color: #000; color: #c5c5c5; font-size: 70%; } @media (min-width:768px){ html,body{ height: 100%; } } </style> <script src="https://www.google.com/recaptcha/api.js" async defer></script> </head> <body> <section class="container"> <div class="customer-logo-wrapper"> <div class="customer-logo"> <img src='' alt="Logo"/> </div> </div> <div class="page-title-wrapper"> <div class="page-title"> <h1>Please verify you are a human</h1> </div> </div> <div class="content-wrapper"> <div class="content"> <p> Please click "I am not a robot" to continue </p> <div class="g-recaptcha" data-sitekey="6Lcj-R8TAAAAABs3FrRPuQhLMbp5QrHsHufzLf7b" data-callback="handleCaptcha" data-theme="dark"> </div> <p> Access to this page has been denied because we believe you are using automation tools to browse the website. </p> <p> Th is may happen as a result of the following: </p> <ul> <li> Javascript is disabled or blocked by an extension (ad blockers for example) </li> <li> Your browser does not support cookies </li> </ul> <p> Please make sure that Javascript and cookies are enabled on your browser and that you are not blocking them from loading. </p> <p> Reference ID: #fb06b930-4085-11e8-8d28-5d147736470b </p> </div> </div> <div class="page-footer-wrapper"> <div class="page-footer"> <p> Powered by <a href="https://www.perimeterx.com">PerimeterX</a> , Inc. </p> </div> </div> </section>  <script> ( function (){ window._pxAppId = 'PXZHh9f9x0'; var clientSrc = '//client.perimeterx.net/' + window._pxAppId + '/main.min.js'; var p = document.getElementsByTagName("script")[0], s = document.createElement("script"); s.async = 1; s.src = clientSrc; p.parentNode.insertBefore(s, p); } () ); </script> <script> window.px_vid="";window.px_uuid="fb06b930-4085-11e8-8d28-5d147736470b"; function handleCaptcha(response){ var vid = ""; var uuid = "fb06b930-4085-11e8-8d28-5d147736470b"; var name = "_pxCaptcha"; var expiryUtc = new Date(Date.now()+1000*10).toUTCString(); var cookie = name + '=' + JSON.stringify({r: response, v: vid, u: uuid}) + '; expires=' + expiryUtc + '; path=/'; document.cookie = cookie; location.reload(); } </script> </body> </html>

**Comment by r0oth3x49** [comment] 2018-04-16 09:16
@yashdeeph709 i cannot reproduce the error for me it is working fine try to use the most recent repo.

**Comment by yashdeeph709** [comment] 2018-04-16 11:14
Ok Sure, I will to pull the latest and retry. And I will close the issue.

**Comment by r0oth3x49** [comment] 2018-04-17 19:09
@yashdeeph709 i 'm considering the problem is solved for you, closing the issue and will w8 for other users to report.

**Closed by r0oth3x49** 2018-04-17 19:09 UTC
Labels: cant-reproduce
