### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by binitdemta** [r0oth3x49/udemy-dl#56] opened 2017-12-21 17:36 UTC
I have been trying to download udemy videos for a while but it gives me an error "Connection error: make sure your internet connection is working" whereas the ping is working fine. By the way i am using a mac os 10.13.2 .

**Comment by r0oth3x49** [comment] 2017-12-21 18:05
@binitdemta thanks for the report i 'm closing this, this is already solved. duplicate of these issues #44, #16

**Closed by r0oth3x49** 2017-12-21 18:05 UTC
Labels: duplicate
