### ISSUE TITLE
URLError cannot download mp4 files

### ISSUE THREAD

**Issue by KNobles** [r0oth3x49/udemy-dl#292] opened 2018-10-29 15:54 UTC
I have an error that pops-up during the download, it only downloads other files fine but not the mp4
here is the error 

![image](https://user-images.githubusercontent.com/14289711/47662452-42af5200-db9b-11e8-8962-ae47816d6b32.png)

**Comment by r0oth3x49** [comment] 2018-10-29 16:49
@KNobles try to upgrade pyOpenSSL version, i cannot reproduce but most of the time when SSL version is old this error occurs so upgrade requests[security].

**Comment by KNobles** [comment] 2018-10-29 18:10
The problem is its already up to date. Might be because I upgraded my distro (I am using parrot security OS). Like few days ago it worked but then I got this message and can't use it :/

**Comment by r0oth3x49** [comment] 2018-10-30 08:05
@KNobles i will try to reproduce on the same OS. by the way i 'm more interested in that `segmentation fault`.

**Comment by KNobles** [comment] 2018-10-30 10:22
downloading after installing the packages doesn't give me the segmentation error anymore
![image](https://user-images.githubusercontent.com/14289711/47711607-e4837d00-dc35-11e8-84ce-11ae38f50574.png)

but i still get the error about internet not working or server aborted
![image](https://user-images.githubusercontent.com/14289711/47711667-067cff80-dc36-11e8-8f05-399f36bed2ec.png)

**Comment by r0oth3x49** [comment] 2018-11-04 09:33
@KNobles i have tested on `Parrot-security-4.2.2_amd64`. after upgrading all of the `requirements` it works fine for me and i cannot reproduce the error you are facing this must be some thing related to your OS. so i 'm  going to close the issue.

Here you go with POCs.
![test](https://user-images.githubusercontent.com/11024397/47961936-10d43a80-e036-11e8-89b1-82a21c469d15.png)
![test1](https://user-images.githubusercontent.com/11024397/47961933-0619a580-e036-11e8-8923-9bc8a657bd52.png)

**Closed by r0oth3x49** 2018-11-04 09:33 UTC
Labels: cant-reproduce

**Comment by urieloko** [comment] 2019-03-20 17:00
check https://github.com/r0oth3x49/udemy-dl/issues/319#issuecomment-464994069
