### ISSUE TITLE
[Errno 22] invalid mode ('wb') or filename

### ISSUE THREAD

**Issue by teamcrisis** [r0oth3x49/udemy-dl#474] opened 2020-02-27 20:58 UTC
**Describe the bug**
I've been using udemy-dl for quite some time. This is the first I've encountered this error.

`[Errno 22] invalid mode ('wb') or filename` upon download. 

`Reason : [Errno 22] invalid mode ('wb') or filename: u'/Volumes/192.168.0.19/data/files/Udemy/website-traffic-generation/02 Creating a Specific & Actionable Traffic Generation Plan.part'`

Seems to be similar or the same as issue #80 

**To Reproduce**
1. Download course `website-traffic-generation`
2. See error

**Python Environment:**
 - OS Platform: MacOS and Linux
 - Python 2.7.17

**Comment by r0oth3x49** [comment] 2020-02-28 07:26
@teamcrisis can you try & reproduce the above error with python3, as i don't have any plan to add fixes for python2 in next version i will completely remove python2 so it will be great if you can try with python3 and let me know if still the same error occurs.

**Comment by teamcrisis** [comment] 2020-02-28 10:21
@r0oth3x49 

Trying `python3` produces `ModuleNotFoundError: No module named 'colorama'`

**Comment by teamcrisis** [comment] 2020-02-28 11:42
I also seem to get error `Reason : [Errno 20] Not a directory:` using python2. Python3 won't run due to missing modules.

**Comment by r0oth3x49** [comment] 2020-02-28 12:11
> 
> 
> I also seem to get error `Reason : [Errno 20] Not a directory:` using python2. Python3 won't run due to missing modules.

you can install the modules same way you installed for python2.

pip install -r requirements.txt

**Comment by teamcrisis** [comment] 2020-02-28 12:53
Ok `Python 3.7.6` is beng used and still same issue `Errno 22`

**Comment by r0oth3x49** [comment] 2020-02-28 13:19
> 
> 
> Ok `Python 3.7.6` is beng used and still same issue `Errno 22`

is it specific to that particular course or what?

**Comment by teamcrisis** [comment] 2020-02-28 13:30
It appears so. I don't have the issue with most other courses but have come across it with at least one other course as well.

**Comment by r0oth3x49** [comment] 2020-02-29 08:14
then i might need your account to reproduce because i don't have access to that course so i can't reproduce.

**Comment by Mihaylov93** [comment] 2020-03-02 01:39
Couldn't reproduce with python 3.8.2 and https://www.udemy.com/course/website-traffic-generation/

**Comment by r0oth3x49** [comment] 2020-03-02 05:15
> 
> 
> Couldn't reproduce with python 3.8.2 and https://www.udemy.com/course/website-traffic-generation/

it means it is working for you too?

**Comment by Mihaylov93** [comment] 2020-03-02 11:06
Yes, it is working for me tried the reported course and all the chapters, and also the reported chapter alone 

> 02 Creating a Specific & Actionable Traffic Generation Plan

Worked fine.
PS: I have Udemy for business and access to courses.

**Comment by r0oth3x49** [comment] 2020-03-02 18:36
> 
> 
> Yes, it is working for me tried the reported course and all the chapters, and also the reported chapter alone
> 
> > 02 Creating a Specific & Actionable Traffic Generation Plan
> 
> Worked fine.
> PS: I have Udemy for business and access to courses.

great thanks for you comment on this. i 'm going to close the issue .

**Closed by r0oth3x49** 2020-03-02 18:36 UTC
Labels: account-needed, cant-reproduce

**Comment by teamcrisis** [comment] 2020-03-05 13:51
Just a follow-up...for some reason the directory had become corrupt. Deleting the directory and redownloading everything fixed the issue.
