### ISSUE TITLE
.txt files skipped during download and get  Udemy returned HTTP Code 416: Requested Range Not Satisfiable.

### ISSUE THREAD

**Issue by Bhuyang** [r0oth3x49/udemy-dl#520] opened 2020-06-22 19:38 UTC
**To Reproduce**
1. Udemy course url: https://udemy.com/course/sap-abap-programming-for-beginners/learn/lecture/200574#overview
2. Use python udemy-dl.py courseURL -k cookies.txt
3. See error when it try to download .txt file.

**Expected behavior**
.txt File should be download.

**Screenshots**
![image](https://user-images.githubusercontent.com/30495645/85328209-f80be780-b4ed-11ea-9849-ba2a40504770.png)

**Python Environment (please complete the following information):**
 - OS Platform: Windows 10
 - Python Version: 3.6.3

**Comment by r0oth3x49** [comment] 2020-06-25 07:14
@Bhuyang i can download txt files easily without any issues i can't reproduce this issue on the courses i have so i 'm closing this issue. you can email me your credentials on `nasir251292@gmail.com` if you want me to test with that particular course.

**Closed by r0oth3x49** 2020-06-25 07:14 UTC
Labels: account-needed, cant-reproduce
