### ISSUE TITLE
assets not downloaded

### ISSUE THREAD

**Issue by anasuti** [r0oth3x49/udemy-dl#507] opened 2020-05-13 22:22 UTC
Some assets are not downloaded (skipped)

To reproduce the error:
- udemy course url: https://www.udemy.com/course/patterns-cplusplus/

you see some errors like this:
[*] : Downloading asset(s)
[*] : Downloading (005 Creational.Creational.LSP.cpp.txt)
[*] : Asset : '005 Creational.Creational.LSP.cpp.txt' (download skipped).
[-] : Udemy returned HTTP Code 416: Requested Range Not Satisfiable

**Python Environment (please complete the following information):**
 - OS Platform: Windows 10 pro
 - Python Version 3.7.3

**Comment by anasuti** [comment] 2020-05-13 22:29
just add a bit of information, as I see that this issue has been already reported.
That error (HTTP Code 416) occurs on the second run of the script. I have deleted all the .part files and relaunched it.
The error I get is the following (only on some assets):
[*] : Downloading asset(s)
[*] : Downloading (128 Behavioral.Visitor.VisitorCodingExercise.cpp.txt)
[*] : 0.75KB/2.35KB 313.33% |##############################################################################################| 15.12kB/s eta -1:59:59s[*] : Asset : '128 Behavioral.Visitor.VisitorCodingExercise.cpp.txt' (download skipped).
[-] : None

**Comment by r0oth3x49** [comment] 2020-05-14 01:15
@anasuti can you share you creds or cookies on email `nasir251292@gmail.com`?  i can't reproduce with the courses i have in my account it works fine for me.
![Capture](https://user-images.githubusercontent.com/11024397/81881720-5322f400-95aa-11ea-9147-d6b3956c0e39.PNG)

**Comment by r0oth3x49** [comment] 2020-05-14 01:18
let move the discussion into #504  i 'm closing this issue as duplicate.

**Closed by r0oth3x49** 2020-05-14 01:18 UTC
