### ISSUE TITLE
Unable to run the script

### ISSUE THREAD

**Issue by vikasnewports** [r0oth3x49/udemy-dl#155] opened 2018-03-17 06:19 UTC
Hello, I have searched and nothing worked for me so I have posted my question again.
I have installed Python3.6 on laptop under Windows 10.
here is the path for python 

    C:\Users\Probook\AppData\Local\Programs\Python\Python36-32
  
I have already this path to my system environment also created the directory in C for project and add that path too in system environment.
 But I am getting failed to even run it . when i run it I have the following error see the screenshot http://prntscr.com/isd3g2

please help me to start using it and do not close this issue its my request

**Comment by vikasnewports** [comment] 2018-03-17 07:24
i have resolved it my own 
by doing this 
pip install -r requirements.txt

**Comment by r0oth3x49** [comment] 2018-03-17 18:19
@vikasnewports great if the issue is solved for you why dint you closed the issue by your self. closing now.

**Closed by r0oth3x49** 2018-03-17 18:19 UTC
